ablation_name: "FarCorner"

# common configs
env: "Farmworld"
eps_length: 100
max_env_actions: 6
context_size: 3
use_context: true
discrete_context: false

# env specific
map: [[" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", "a", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", "a", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", "a", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", "a", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "c", "c", "c"],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "c", "c", "c"],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "c", "c", "c"],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "t", "t", "t", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "t", "t", "t", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "t", "t", "t", " ", " ", " "]]

num_agents: 4
num_towers: 2
num_chickens: 2
sidelength_x: 4
sidelength_y: 4

max_agent_health: 60
max_tower_health: 1
max_chicken_health: 2

chicken_move_prob: 0.0

chicken_cooldown: 200
tower_cooldown: 200

ava_damage: 10

agent_payoff: 0
tower_payoff: 6
chicken_payoff: 6

channels_first: true
use_pixels: false

use_specialization: false
agent_view_range: 2

evolve_contexts: false