ablation_name: Patience
evolve_steps: 400

# common configs
env: "Farmworld"
eps_length: 200
max_env_actions: 6
context_size: 3
use_context: true
discrete_context: false

# env specific
num_agents: 1
num_towers: 2
num_chickens: 0
sidelength_x: 2
sidelength_y: 2

max_agent_health: 20
max_tower_health: 1
max_chicken_health: 2

chicken_move_prob: 0.0

chicken_cooldown: 200
tower_cooldown: 30

ava_damage: 0

agent_payoff: 0
tower_payoff: 20
chicken_payoff: 0

channels_first: true
use_pixels: false

use_specialization: false
agent_view_range: 2

evolve_contexts: false