# Larger map baseline using context loss, entropy, and no enforced specialization, context size of 6

env_conf:
  ablation_name: "PoisonChicken"
  evolve_steps: 400

  # common configs
  env: "Farmworld"
  eps_length: 100
  max_env_actions: 6
  context_size: 3
  use_context: true
  discrete_context: false

  # env specific
  num_agents: 1
  num_towers: 2
  num_chickens: 2
  sidelength_x: 5
  sidelength_y: 5

  max_agent_health: 25
  max_tower_health: 1
  max_chicken_health: 2

  chicken_move_prob: 0.0

  chicken_cooldown: 2
  tower_cooldown: 2

  ava_damage: 0

  agent_payoff: 0
  tower_payoff: 10
  chicken_payoff: -15

  channels_first: true
  use_pixels: false

  use_specialization: false
  agent_view_range: 2

  evolve_contexts: false

training_conf:
  # model configuration
  model: "ContextMult"
  use_mi_discrim: false
  hidden_dim: 128

  # policy configuration
  trainer: "Context"
  vf_loss_coeff: 1
  entropy_coeff: 0.05
  context_loss_coeff: 0.1

  lr: 0.0003
  train_batch_size: 4_000
  sgd_minibatch_size: 2_000
  num_sgd_iter: 10

  rollout_fragment_length: 100
  batch_mode: "complete_episodes"
  count_steps_by: "agent_steps"

  timesteps_total: 1_000_000
  training_iteration: 400