
env_conf:
  ablation_name: WallBarrier

  # common configs
  env: "Farmworld"
  eps_length: 100
  max_env_actions: 6
  context_size: 3
  use_context: true
  discrete_context: false

  # env specific
  map: [[" ", " ", " ", " ", " ", " ", " ", " ", " "],
        [" ", " ", " ", " ", " ", " ", " ", " ", " "],
        [" ", " ", " ", " ", " ", " ", " ", " ", " "],
        [" ", " ", " ", " ", " ", " ", " ", " ", " "],
        [" ", " ", " ", " ", " ", " ", " ", " ", " "],
        [" ", " ", " ", " ", "w", " ", " ", " ", " "],
        [" ", " ", " ", " ", "w", " ", " ", " ", " "],
        [" ", " ", " ", " ", "w", " ", " ", " ", " "],
        [" ", " ", " ", " ", "w", " ", " ", " ", " "],
        [" ", " ", " ", " ", "w", " ", " ", " ", " "],
        [" ", " ", " ", " ", "w", " ", "c", "c", "c"],
        [" ", " ", " ", " ", "w", " ", "c", "c", "c"],
        [" ", "a", "a", "a", "w", " ", "c", "c", "c"],
        [" ", " ", " ", " ", "w", " ", "c", "c", "c"]]

  num_agents: 4
  num_towers: 2
  num_chickens: 2
  sidelength_x: 4
  sidelength_y: 4

  max_agent_health: 40
  max_tower_health: 1
  max_chicken_health: 2

  chicken_move_prob: 0.0

  chicken_cooldown: 200
  tower_cooldown: 200

  ava_damage: 10

  agent_payoff: 0
  tower_payoff: 6
  chicken_payoff: 6

  channels_first: true
  use_pixels: false

  use_specialization: false
  agent_view_range: 2

  evolve_contexts: false

training_conf:
  # model configuration
  model: "ContextConcat"
  use_mi_discrim: false
  hidden_dim: 64

  # policy configuration
  trainer: "PPO"
  vf_loss_coeff: 1
  entropy_coeff: 0.1
  context_loss_coeff: 1

  lr: 0.0003
  train_batch_size: 4_000
  sgd_minibatch_size: 2_000
  num_sgd_iter: 10

  rollout_fragment_length: 100
  batch_mode: "complete_episodes"
  count_steps_by: "agent_steps"

  timesteps_total: 4_000_000
  training_iteration: 400