agent_payoff: 0
agent_view_range: 2
ava_damage: 0
channels_first: true
chicken_cooldown: 10
chicken_move_prob: 0.0
chicken_payoff: 4
context_sampler: l2
context_size: 3
discrete_context: false
env: Farmworld
eps_length: 200
max_agent_health: 15
max_chicken_health: 2
max_env_actions: 6
max_tower_health: 1
num_agents: 8
num_chickens: 8
num_towers: 8
sidelength_x: 10
sidelength_y: 10
tower_cooldown: 10
tower_payoff: 4
use_context: true
use_pixels: false
use_specialization: true